export type FieldTypes =
  | 'richtext'
  | 'color'
  | 'text'
  | 'file'
  | 'password'
  | 'radio'
  | 'checkbox'
  | 'range'
  | 'select'
  | 'combobox'
  | 'multiselect'
  | 'datepicker'
  | 'sheetpicker'
  | 'switch'
  | 'switchlist'
  | 'textarea';
